directories:
  output: release-builds
  buildResources: build
appId: com.Hadassah.hrportal
productName: HR Portal
icon: assets/icon.ico
files:
  - filter:
      - build/**/*
      - main.js
      - preload.js
      - index.html
      - electron/**/*
extraResources:
  - from: node_modules/sqlite3/lib/binding
    to: sqlite3
    filter:
      - '*.node'
win:
  target:
    - portable
publish:
  provider: generic
  url: \\ism\hr\IT\portalHR\update
electronVersion: 24.8.8
